### ISSUE TITLE
Update UI for Conditions and Observations Report panels

### ISSUE THREAD

**Issue by dtedder** [Esri/dynamic-situational-awareness-qt#384]
The `Conditions` and `Observations Report` panels UIs needs to be updated. The text on the Back and Next buttons are not visible (instead you see ellipses).  Also, hitting the X at the bottom ('Cancel')  does not cancel the panel (hitting the X in the upper right-hand corner does). 
![image](https://github.com/Esri/dynamic-situational-awareness-qt/assets/3383476/ccfba940-e582-445c-a2a1-d1f257a7d3f9)

This might be happening in other places too, need to log any UI issues here.

**Comment by dtedder** [comment]
@kerryrobinson These look ok? I tested on iOS actual device and things appear to scale fairly well.

![image](https://github.com/user-attachments/assets/4ec8b431-3876-4c81-9bc6-e28f2e71b9a1)![image](https://github.com/user-attachments/assets/6185eb00-c54d-4244-a41b-b7571bbc23c2)![image](https://github.com/user-attachments/assets/81537b86-1e6d-497b-9ee7-7c86a60cf279)![image](https://github.com/user-attachments/assets/f625f8af-541d-40b9-bf50-954a7eeab750)

**Comment by kerryrobinson** [comment]
Yes that looks much better and at least works for now, since the text is readable.  It would be great if the text was larger (but didn't get cut off). The buttons could also be square instead of rounded which might accommodate this. If this doesn't end up being a simple fix, we can come back to this later and look at larger UI updates to the app.

**Comment by kerryrobinson** [comment]
This looks much better now.  👍
